export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/home/index',
    'pages/plan/index',
    'pages/ai/index',
    'pages/ledger/index',
    'pages/profile/index',
  ],
  subPackages: [
    { root: 'subpackage/common', pages: ['profile-info', 'plan-history', 'ai-history'] },
    { root: 'pages/account', pages: ['detail', 'select', 'revoke-confirm'] },
    { root: 'pages/settings', pages: ['privacy', 'data-usage', 'notifications', 'about'] },
    { root: 'pages/period', pages: ['edit', 'detail'] },
    { root: 'pages/item', pages: ['detail', 'edit'] },
    { root: 'pages/review', pages: ['list', 'index'] },
    { root: 'pages/impact', pages: ['detail'] },
    { root: 'pages/draft', pages: ['detail'] },
    { root: 'pages/offers', pages: ['index'] },
    { root: 'pages/catalog', pages: ['detail'] },
    { root: 'pages/purchase', pages: ['detail'] },
    { root: 'pages/orders', pages: ['index'] },
    { root: 'pages/order', pages: ['detail'] },
    { root: 'pages/refund', pages: ['detail'] },
    { root: 'pages/payment', pages: ['handoff'] },
    { root: 'pages/operation', pages: ['detail'] },
    { root: 'pages/emergency', pages: ['index'] },
    { root: 'pages/adjustment', pages: ['detail'] },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F4F7F5',
    navigationBarTitleText: '行止',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F4F7F5',
  },
  tabBar: {
    color: '#75817B',
    selectedColor: '#2F6F5A',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index', text: '首页',
        iconPath: 'assets/tabbar/home-normal.png', selectedIconPath: 'assets/tabbar/home-selected.png',
      },
      {
        pagePath: 'pages/plan/index', text: '计划',
        iconPath: 'assets/tabbar/plan-normal.png', selectedIconPath: 'assets/tabbar/plan-selected.png',
      },
      {
        pagePath: 'pages/ai/index', text: '行止AI',
        iconPath: 'assets/tabbar/ai-normal.png', selectedIconPath: 'assets/tabbar/ai-selected.png',
      },
      {
        pagePath: 'pages/ledger/index', text: '账目',
        iconPath: 'assets/tabbar/ledger-normal.png', selectedIconPath: 'assets/tabbar/ledger-selected.png',
      },
      {
        pagePath: 'pages/profile/index', text: '我的',
        iconPath: 'assets/tabbar/profile-normal.png', selectedIconPath: 'assets/tabbar/profile-selected.png',
      },
    ],
  },
});
