export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/home/index',
    'pages/plan/index',
    'pages/ai/index',
    'pages/ledger/index',
    'pages/profile/index',
    'pages/profile/info',
    'pages/account/detail',
    'pages/account/select',
    'pages/account/revoke-confirm',
    'pages/impact/detail',
    'pages/item/detail',
    'pages/settings/privacy',
    'pages/settings/data-usage',
    'pages/settings/notifications',
    'pages/settings/about',
    'pages/plan/history',
    'pages/review/list',
    'pages/ai/history',
    'pages/period/edit',
    'pages/period/detail',
    'pages/item/edit',
    'pages/draft/detail',
    'pages/offers/index',
    'pages/catalog/detail',
    'pages/purchase/detail',
    'pages/orders/index',
    'pages/order/detail',
    'pages/refund/detail',
    'pages/payment/handoff',
    'pages/operation/detail',
    'pages/emergency/index',
    'pages/adjustment/detail',
    'pages/review/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F4F7F5',
    navigationBarTitleText: '行止',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F4F7F5',
  },
  tabBar: {
    color: '#75817B',
    selectedColor: '#2F6F5A',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index', text: '首页',
        iconPath: 'assets/tabbar/home-normal.png', selectedIconPath: 'assets/tabbar/home-selected.png',
      },
      {
        pagePath: 'pages/plan/index', text: '计划',
        iconPath: 'assets/tabbar/plan-normal.png', selectedIconPath: 'assets/tabbar/plan-selected.png',
      },
      {
        pagePath: 'pages/ai/index', text: '行止AI',
        iconPath: 'assets/tabbar/ai-normal.png', selectedIconPath: 'assets/tabbar/ai-selected.png',
      },
      {
        pagePath: 'pages/ledger/index', text: '账目',
        iconPath: 'assets/tabbar/ledger-normal.png', selectedIconPath: 'assets/tabbar/ledger-selected.png',
      },
      {
        pagePath: 'pages/profile/index', text: '我的',
        iconPath: 'assets/tabbar/profile-normal.png', selectedIconPath: 'assets/tabbar/profile-selected.png',
      },
    ],
  },
});
