// Keep this compatibility barrel so page code has one local import path while
// the source of truth lives in the shared frontend/backend contract package.
export type {
  Adjustment,
  AdjustmentConfirmation,
  AdjustmentDetail,
  AdjustmentOption,
  AftercareConfirmation,
  AftercarePreview,
  AgentRun,
  AgentRunSummary,
  ApiEnvelope,
  BudgetItem,
  BudgetItemInput,
  BudgetPeriod,
  ConsumerOrder,
  ConsumerPreferences,
  FinanceAccountFacts,
  FundingAssessment,
  LedgerEntry,
  Offer,
  OfferQuote,
  Operation,
  OrderAftercare,
  PaymentHandoff,
  PaymentReadiness,
  PaymentRecheck,
  PeriodEvent,
  PeriodReview,
  PlanningDraft,
  PurchaseIntent,
  PurchaseIntentProposal,
  RuntimeStatus,
  ConsumerSessionUser as User,
} from '@xingzhi/contracts';
