<script setup lang="ts">
import{ref}from'vue';import Taro,{useLoad}from'@tarojs/taro';import PageShell from '@/components/PageShell.vue';import SectionCard from '@/components/SectionCard.vue';import StatePanel from '@/components/StatePanel.vue';import FactRow from '@/components/FactRow.vue';import StatusBadge from '@/components/StatusBadge.vue';import{api}from'@/lib/api';import{errorMessage}from'@/lib/errors';import{shortDate,yuan}from'@/lib/format';import type{ConsumerOrder}from'@/lib/types';
const id=ref(''),order=ref<ConsumerOrder|null>(null),loading=ref(true),saving=ref(false),error=ref('');async function load(){try{order.value=(await api.order(id.value)).data;}catch(e){error.value=errorMessage(e);}finally{loading.value=false;}}useLoad(o=>{id.value=o.id??'';void load();});
const label=(s:string)=>({pending:'待付款',paid:'已付款',unknown:'结果待核验',closed:'已关闭',failed:'付款失败'}[s]??s);
const orderLabel=(s:string)=>({created:'已建立',fulfilling:'履约中',completed:'已完成',cancellation_processing:'取消处理中',cancellation_rejected:'取消未通过',cancelled:'已取消'}[s]??s);
const operationLabel=(s:string)=>({simulate_payment:'模拟付款',sandbox_payment_handoff:'付款交接',sandbox_payment_recheck:'付款查单',simulate_close:'模拟关单',sandbox_close:'渠道关单',simulate_refund_batch:'模拟退款',sandbox_refund:'渠道退款',sandbox_refund_recheck:'退款查单',merchant_cancellation_review:'取消审核'}[s]??s);
function handoff(){void Taro.navigateTo({url:`/pages/payment/handoff?orderId=${id.value}`});}
async function aftercare(action:'close'|'cancel'){if(saving.value)return;saving.value=true;try{const preview=(await api.aftercarePreview(id.value,action)).data;const ok=await Taro.showModal({title:action==='close'?'确认关闭待付订单？':'确认提交取消退款？',content:`费用 ${yuan(preview.feeMinor)}，预计退款 ${yuan(preview.expectedRefundMinor)}。渠道成功不代表资金已经到账。`,confirmText:'确认提交'});if(ok.confirm){const result=(await api.confirmAftercare(id.value,{previewId:preview.previewId,acceptedFeeMinor:preview.feeMinor,acceptedRefundMinor:preview.expectedRefundMinor,confirmedByUser:true})).data;if(result.operationId)await Taro.navigateTo({url:`/pages/operation/detail?id=${result.operationId}&orderId=${id.value}`});else await load();}}catch(e){error.value=errorMessage(e);}finally{saving.value=false;}}
</script>
<template><PageShell title="订单详情" subtitle="付款、关闭和退款状态分层展示" compact><template #hero><button class="back" @tap="Taro.navigateBack()">‹</button></template><StatePanel v-if="loading" title="正在读取订单"/><StatePanel v-else-if="error&&!order" title="订单暂时不可用" :detail="error" tone="error"><button class="secondary-button retry" @tap="load">重新加载</button></StatePanel><template v-else-if="order"><SectionCard><view class="row-between"><text class="title">{{order.itemName}}</text><StatusBadge :label="label(order.paymentStatus)" :tone="order.paymentStatus==='paid'?'success':order.paymentStatus==='unknown'?'warning':'info'"/></view><FactRow label="订单金额" :value="yuan(order.amountMinor)" emphasis/><FactRow label="环境" :value="order.environment==='simulation'?'本地模拟':'支付宝沙箱'"/><FactRow label="订单状态" :value="orderLabel(order.status)"/><FactRow label="已到账退款" :value="yuan(order.refundedMinor)"/><FactRow label="更新时间" :value="shortDate(order.updatedAt)"/><button v-if="order.operationId" class="secondary-button operation-button" @tap="Taro.navigateTo({url:`/pages/operation/detail?id=${order.operationId}&orderId=${id}`})">{{['succeeded','failed','pending_review'].includes(order.operationState??'')?'查看最近处理结果':'继续查看处理进度'}}</button><button v-if="order.status.includes('cancel')||order.refundedMinor>0" class="secondary-button operation-button" @tap="Taro.navigateTo({url:`/pages/refund/detail?orderId=${id}`})">查看退款与善后时间线</button><view v-if="order.paymentStatus==='pending'" class="actions"><button class="primary-button" :loading="saving" @tap="handoff">继续付款交接</button><button class="secondary-button" @tap="aftercare('close')">关闭待付订单</button></view><button v-else-if="order.paymentStatus==='paid'&&order.refundedMinor===0" class="secondary-button full" @tap="aftercare('cancel')">申请取消退款</button><view class="notice notice--info note">退款分为申请受理、渠道处理、账户到账三层；只有核验到账后才会增加可用现金。</view><view v-if="error" class="notice notice--error note">{{error}}</view></SectionCard><SectionCard v-if="order.operations?.length" class="history"><text class="title">处理记录</text><button v-for="operation in order.operations" :key="operation.operationId" class="history-row" @tap="Taro.navigateTo({url:`/pages/operation/detail?id=${operation.operationId}&orderId=${id}`})"><view><text>{{operationLabel(operation.operationType)}}</text><text>{{shortDate(operation.updatedAt)}} · {{operation.purpose}}</text></view><StatusBadge :label="operation.operationState==='succeeded'?'已完成':operation.operationState==='failed'?'失败':operation.operationState==='pending_review'?'待复核':'处理中'" :tone="operation.operationState==='succeeded'?'success':operation.operationState==='failed'?'warning':'info'"/></button></SectionCard></template></PageShell></template>
<style lang="scss">@use '../../styles/tokens' as *;.back{position:absolute;right:28px;top:calc(34px + env(safe-area-inset-top));width:64px;height:64px;border-radius:50%;font-size:42px}.title{font-size:28px;font-weight:720}.actions{display:grid;gap:12px;margin-top:22px}.actions button,.full,.operation-button{width:100%}.full,.note,.operation-button{margin-top:18px}.retry{margin-top:18px}.history{margin-top:18px}.history-row{display:flex;width:100%;align-items:center;justify-content:space-between;gap:16px;padding:18px 0;text-align:left}.history-row+.history-row{border-top:1px solid $border}.history-row>view{min-width:0;flex:1}.history-row text{display:block;font-size:22px}.history-row text+text{margin-top:6px;color:$text-secondary;font-size:19px;line-height:1.45}</style>
