<script setup lang="ts">
import { computed, ref } from 'vue';
import Taro, { useLoad } from '@tarojs/taro';
import PageShell from '@/components/PageShell.vue';import SectionCard from '@/components/SectionCard.vue';import StatePanel from '@/components/StatePanel.vue';import FactRow from '@/components/FactRow.vue';import StatusBadge from '@/components/StatusBadge.vue';
import { api } from '@/lib/api';import { errorMessage } from '@/lib/errors';import { fundingLabel, shortDate, yuan } from '@/lib/format';import type { BudgetItem, BudgetPeriod, FundingAssessment, Offer, OfferQuote } from '@/lib/types';
const period=ref<BudgetPeriod|null>(null),item=ref<BudgetItem|null>(null),offers=ref<Offer[]>([]),selected=ref<Offer|null>(null),quote=ref<OfferQuote|null>(null),assessment=ref<FundingAssessment|null>(null);const loading=ref(true),saving=ref(false),error=ref('');
const difference=computed(()=>quote.value&&item.value?quote.value.priceMinor-item.value.userEstimatedAmountMinor:null);
useLoad(async o=>{try{period.value=(await api.period(o.periodId??'')).data;item.value=period.value.items.find(v=>v.itemId===o.itemId)??null;if(!item.value)throw new Error('未找到计划项目。');offers.value=(await api.offers(item.value.plannedOn,item.value.categoryCode)).data.items;}catch(e){error.value=errorMessage(e);}finally{loading.value=false;}});
async function choose(value:Offer){selected.value=value;quote.value=null;assessment.value=null;error.value='';try{quote.value=(await api.offerQuote(value.id,item.value!.plannedOn)).data;assessment.value=(await api.assessPurchase({periodId:period.value!.period.periodId,budgetItemId:item.value!.itemId,quoteId:quote.value.quoteId,expectedFinancialVersion:period.value!.basis.financialVersion,expectedPeriodVersion:period.value!.basis.periodVersion,expectedQuoteVersion:quote.value.quoteVersion,mode:'preview'})).data;}catch(e){error.value=errorMessage(e);}}
async function createIntent(){if(!period.value||!item.value||!quote.value||!assessment.value||assessment.value.status!=='allowed'||saving.value)return;saving.value=true;try{const result=await api.createPurchaseIntent({periodId:period.value.period.periodId,budgetItemId:item.value.itemId,quoteId:quote.value.quoteId,assessmentId:assessment.value.assessmentId,expectedFinancialVersion:assessment.value.financialVersion,expectedPeriodVersion:assessment.value.periodVersion,expectedQuoteVersion:assessment.value.quoteVersion});const id=String(result.data.purchaseIntentId??'');await Taro.redirectTo({url:`/pages/purchase/detail?id=${id}`});}catch(e){error.value=errorMessage(e);}finally{saving.value=false;}}
</script>
<template><PageShell title="选择候选" subtitle="报价与计划估价分开核对" compact><template #hero><button class="back" @tap="Taro.navigateBack()">‹</button></template><StatePanel v-if="loading" title="正在读取候选"/><StatePanel v-else-if="error&&!offers.length" title="候选暂时不可用" :detail="error" tone="error"/><template v-else><SectionCard v-if="item"><text class="title">{{item.title}}</text><FactRow label="计划日期" :value="shortDate(item.plannedOn)"/><FactRow label="原计划估价" :value="yuan(item.userEstimatedAmountMinor)"/></SectionCard><view class="list"><SectionCard v-for="offer in offers" :key="offer.id" class="offer"><view class="row-between"><view><text class="title">{{offer.name}}</text><text class="muted">{{offer.description}}</text></view><text class="price">{{yuan(offer.displayPriceMinor)}}</text></view><text class="rule">{{offer.ruleLabel}}</text><view class="offer-actions"><button class="text-button" @tap="Taro.navigateTo({url:`/pages/catalog/detail?id=${offer.id}&periodId=${period?.period.periodId}&itemId=${item?.itemId}`})">查看详情</button><button class="secondary-button" @tap="choose(offer)">核对报价</button></view></SectionCard></view><StatePanel v-if="!offers.length" title="该日期暂无可用候选" detail="可以返回修改计划日期后重试。"/><SectionCard v-if="selected&&quote&&assessment" class="decision"><view class="row-between"><text class="title">确认前核对</text><StatusBadge :label="fundingLabel(assessment.status)" :tone="assessment.status==='allowed'?'success':'warning'"/></view><FactRow label="实时报价" :value="yuan(quote.priceMinor)" emphasis/><FactRow label="相对估价变化" :value="difference===null?'—':`${difference>=0?'+':''}${yuan(difference)}`"/><FactRow label="报价有效至" :value="shortDate(quote.validUntil)"/><FactRow label="预计缺口" :value="yuan(assessment.shortfallMinor)"/><button class="primary-button full" :disabled="assessment.status!=='allowed'||saving" :loading="saving" @tap="createIntent">建立待确认意图</button><view v-if="assessment.status!=='allowed'" class="recovery"><button class="secondary-button" @tap="Taro.navigateTo({url:`/pages/impact/detail?periodId=${period?.period.periodId}`})">查看资金影响</button><button class="secondary-button" @tap="Taro.switchTab({url:'/pages/ai/index'})">问问行止</button></view></SectionCard><view v-if="error" class="notice notice--error err">{{error}}</view></template></PageShell></template>
<style lang="scss">@use '../../styles/tokens' as *;.back{position:absolute;right:28px;top:calc(34px + env(safe-area-inset-top));width:64px;height:64px;border-radius:50%;font-size:42px}.list{display:grid;gap:14px;margin-top:16px}.title,.muted{display:block}.title{font-size:27px;font-weight:700}.muted{max-width:420px;margin-top:8px;color:$text-secondary;font-size:21px;line-height:1.5}.price{font-size:28px;font-weight:720}.rule{display:block;margin-top:16px;color:$text-tertiary;font-size:20px}.offer-actions,.recovery{display:flex;justify-content:flex-end;gap:12px;margin-top:18px}.text-button{color:$brand-primary;font-size:22px;font-weight:650}.decision{margin-top:18px}.full{width:100%;margin-top:22px}.recovery button{flex:1}.err{margin-top:16px}</style>
