<script setup lang="ts">
import { ref } from 'vue';import Taro,{useDidShow,useLoad} from '@tarojs/taro';
import BottomSheet from '@/components/BottomSheet.vue';import FactRow from '@/components/FactRow.vue';import PageShell from '@/components/PageShell.vue';import PlanItemCard from '@/components/PlanItemCard.vue';import SectionCard from '@/components/SectionCard.vue';import SectionHeader from '@/components/SectionHeader.vue';import StatePanel from '@/components/StatePanel.vue';import StatusBadge from '@/components/StatusBadge.vue';
import {api} from '@/lib/api';import {errorMessage} from '@/lib/errors';import {fundingLabel,shortDate,yuan} from '@/lib/format';import type{BudgetPeriod}from '@/lib/types';
const id=ref('');const period=ref<BudgetPeriod|null>(null);const loading=ref(true);const error=ref('');const activating=ref(false);const closing=ref(false);const confirmOpen=ref(false);
useLoad(options=>{id.value=options.id??'';});useDidShow(()=>{if(id.value)void load();});
async function load(){loading.value=true;error.value='';try{period.value=(await api.period(id.value)).data;}catch(reason){error.value=errorMessage(reason);}finally{loading.value=false;}}
async function activate(){if(!period.value||activating.value)return;activating.value=true;error.value='';try{period.value=(await api.activatePeriod(id.value,{expectedFinancialVersion:period.value.basis.financialVersion,expectedPeriodVersion:period.value.period.periodVersion,confirmedNecessities:true})).data;confirmOpen.value=false;}catch(reason){error.value=errorMessage(reason);confirmOpen.value=false;}finally{activating.value=false;}}
async function closePeriod(){if(!period.value||closing.value)return;const accepted=await Taro.showModal({title:'结束并归档本周期？',content:'只有月份已经结束且没有待确认、支付、退款或复核事项时才能归档。归档后计划只读，但历史订单和复盘仍可查看。',confirmText:'确认归档'});if(!accepted.confirm)return;closing.value=true;error.value='';try{period.value=(await api.closePeriod(id.value,{expectedPeriodVersion:period.value.period.periodVersion,confirmedByUser:true,reason:'月度周期结束后由用户确认归档'})).data;Taro.showToast({title:'周期已归档',icon:'success'});}catch(reason){error.value=errorMessage(reason);}finally{closing.value=false;}}
function editItem(itemId?:string){void Taro.navigateTo({url:`/pages/item/edit?periodId=${id.value}${itemId?`&itemId=${itemId}`:''}`});}
function openItem(itemId:string){void Taro.navigateTo({url:`/pages/item/detail?periodId=${id.value}&itemId=${itemId}`});}
function findOffers(itemId:string){void Taro.navigateTo({url:`/pages/offers/index?periodId=${id.value}&itemId=${itemId}`});}
</script>
<template><PageShell title="计划详情" :subtitle="period?`${period.period.monthStart.slice(0,7).replace('-','年')}月 · ${period.period.status==='draft'?'草稿':period.period.status==='active'?'执行中':'已结束'}`:'读取中'" compact><template #hero><button class="back" @tap="Taro.navigateBack()">‹</button></template>
<StatePanel v-if="loading" title="正在核对计划"/><StatePanel v-else-if="error&&!period" title="计划暂时不可用" :detail="error" tone="error"><button class="secondary-button retry" @tap="load">重新加载</button></StatePanel><template v-else-if="period"><view v-if="error" class="notice notice--error page-error">{{error}}</view>
<SectionCard><view class="row-between"><text class="card-title">资金影响</text><StatusBadge :label="fundingLabel(period.forecast.status)" :tone="period.forecast.status==='allowed'?'success':period.forecast.status==='unknown'?'info':'warning'"/></view><FactRow label="确认资金" :value="yuan(period.basis.confirmedCashMinor)"/><FactRow label="保留目标" :value="yuan(period.basis.savingsTargetMinor)"/><FactRow label="必要安排" :value="yuan(period.basis.essentialRemainingMinor)"/><FactRow label="可调计划" :value="yuan(period.basis.adjustablePlannedMinor)"/><FactRow label="预计最低" :value="yuan(period.basis.minimumProjectedCashMinor)" emphasis/><FactRow label="关键日期" :value="shortDate(period.basis.minimumCashOn)"/><button v-if="period.period.status!=='closed'" class="link-button edit-target" @tap="Taro.navigateTo({url:`/pages/period/edit?id=${id}`})">调整保留目标 ›</button></SectionCard>
<SectionHeader title="本月项目" :action="period.period.status==='closed'?undefined:'新增'" @action="editItem()"/><view v-if="period.items.filter(item=>item.status!=='cancelled').length" class="items"><view v-for="item in period.items.filter(item=>item.status!=='cancelled')" :key="item.itemId" class="item-wrap"><PlanItemCard :item="item" :group="period.period.status==='draft'?'draft':'active'" :forecast-status="period.forecast.status" supporting-text="查看状态、影响与下一步" @open="openItem(item.itemId)"/><button v-if="period.period.status==='active'&&item.kind==='planned_spend'&&item.status==='planned'" class="secondary-button offer-button" @tap="findOffers(item.itemId)">查看候选与报价</button></view></view><StatePanel v-else title="还没有计划项目" detail="先补充必要支出和想安排的事情，再激活本月预算。"/>
<button v-if="period.period.status==='draft'" class="primary-button activate" @tap="confirmOpen=true">确认必要支出并激活</button><view v-else class="period-actions"><button v-if="period.period.status==='active'" class="secondary-button" @tap="Taro.navigateTo({url:`/pages/emergency/index?periodId=${id}`})">记录意外支出</button><button class="secondary-button" @tap="Taro.navigateTo({url:`/pages/review/index?periodId=${id}`})">查看月度复盘</button><button class="secondary-button" @tap="Taro.navigateTo({url:'/pages/orders/index'})">订单与确认</button><button v-if="period.period.status==='active'" class="secondary-button close-period" :loading="closing" @tap="closePeriod">结束并归档本周期</button></view><view v-if="period.period.status==='closed'" class="notice notice--info archived">本周期已经归档，计划和金额只读；订单善后、历史账目与月度复盘仍可继续查看。</view></template></PageShell>
<BottomSheet :model-value="confirmOpen" title="确认激活本月预算" description="请确认必要支出已逐项填写；如果确实为零，也表示你已明确确认。" primary-text="确认并激活" secondary-text="再检查一下" @update:model-value="confirmOpen=$event" @primary="activate"><template v-if="period"><FactRow label="必要安排" :value="yuan(period.basis.essentialRemainingMinor)" emphasis/><FactRow label="保留目标" :value="yuan(period.basis.savingsTargetMinor)"/><FactRow label="当前依据" :value="period.basis.dataStatus==='observed'?'资金事实完整':'资金依据尚不完整'"/></template></BottomSheet>
</template><style lang="scss">@use '../../styles/tokens' as *;.back{position:absolute;z-index:4;top:calc(34px + env(safe-area-inset-top));right:28px;width:64px;height:64px;color:$brand-deep;background:rgba(255,255,255,.7);border-radius:50%;font-size:44px}.retry{margin:20px auto 0}.page-error{margin-bottom:16px}.card-title{font-size:28px;font-weight:700}.edit-target{display:block;margin:20px auto 0}.items{display:grid;gap:14px}.item-wrap{display:grid;gap:8px}.offer-button{width:100%}.activate{width:100%;margin-top:26px}.period-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:24px}.period-actions button{width:100%}.period-actions button:last-child{grid-column:1/-1}.close-period{color:$danger}.archived{margin-top:18px}@media screen and (max-width:360px){.period-actions{grid-template-columns:1fr}.period-actions button:last-child{grid-column:auto}}</style>
