<script setup lang="ts">
import{computed,ref}from'vue';import Taro,{useDidShow,useLoad}from'@tarojs/taro';import PageShell from '@/components/PageShell.vue';import SectionCard from '@/components/SectionCard.vue';import StatePanel from '@/components/StatePanel.vue';import FactRow from '@/components/FactRow.vue';import StatusBadge from '@/components/StatusBadge.vue';import{api}from'@/lib/api';import{errorMessage}from'@/lib/errors';import{shortDate,yuan}from'@/lib/format';import type{PurchaseIntent}from'@/lib/types';
const id=ref(''),intent=ref<PurchaseIntent|null>(null),loading=ref(true),saving=ref(false),error=ref('');let loadSequence=0;async function load(){const sequence=++loadSequence;loading.value=true;error.value='';try{const result=(await api.purchaseIntent(id.value)).data;if(sequence===loadSequence)intent.value=result;}catch(e){if(sequence===loadSequence)error.value=errorMessage(e);}finally{if(sequence===loadSequence)loading.value=false;}}useLoad(o=>{id.value=o.id??'';});useDidShow(()=>{if(id.value)void load();});
const expired=computed(()=>Boolean(intent.value&&intent.value.status==='proposed'&&Date.parse(intent.value.expiresAt)<=Date.now()));
async function confirm(){if(!intent.value||saving.value)return;const ok=await Taro.showModal({title:'确认按报价购买？',content:`将按 ${yuan(intent.value.quotedAmountMinor)} 建立订单，付款仍需下一步操作。`,confirmText:'确认建立'});if(!ok.confirm)return;saving.value=true;try{const r=await api.confirmPurchaseIntent(intent.value.purchaseIntentId,{acceptedAmountMinor:intent.value.quotedAmountMinor,expectedFinancialVersion:intent.value.financialVersion,expectedPeriodVersion:intent.value.periodVersion,expectedQuoteVersion:intent.value.quoteVersion,confirmedByUser:true});await Taro.redirectTo({url:`/pages/order/detail?id=${r.data.order.orderId}`});}catch(e){error.value=errorMessage(e);}finally{saving.value=false;}}
async function reject(){if(!intent.value||saving.value)return;const ok=await Taro.showModal({title:'放弃这次购买确认？',content:'放弃后不会建立订单；计划项目会保留，之后仍可重新选择候选。',confirmText:'确认放弃'});if(!ok.confirm)return;saving.value=true;try{await api.rejectPurchaseIntent(intent.value.purchaseIntentId);intent.value.status='rejected';}catch(e){error.value=errorMessage(e);}finally{saving.value=false;}}
function retryQuote(){if(intent.value)void Taro.redirectTo({url:`/pages/offers/index?periodId=${intent.value.periodId}&itemId=${intent.value.budgetItemId}`});}
</script>
<template><PageShell title="购买确认" subtitle="金额、版本和规则由你最后确认" compact><template #hero><button class="back" @tap="Taro.navigateBack()">‹</button></template><StatePanel v-if="loading" title="正在读取购买意图"/><StatePanel v-else-if="error&&!intent" title="购买意图不可用" :detail="error" tone="error"/><SectionCard v-else-if="intent"><view class="row-between"><text class="title">{{intent.offerName}}</text><StatusBadge :label="expired?'报价已过期':intent.status==='proposed'?'等待确认':intent.status==='ordered'?'已建立订单':intent.status==='rejected'?'已放弃':'已结束'" :tone="intent.status==='proposed'&&!expired?'info':intent.status==='ordered'?'success':'neutral'"/></view><FactRow label="对应计划" :value="intent.itemTitle"/><FactRow label="计划估价" :value="yuan(intent.userEstimatedAmountMinor)"/><FactRow label="确认报价" :value="yuan(intent.quotedAmountMinor)" emphasis/><FactRow label="服务日期" :value="shortDate(intent.plannedOn)"/><FactRow label="确认有效至" :value="shortDate(intent.expiresAt)"/><view v-if="expired" class="notice notice--warning note">本次报价和资金评估已经过期，不能继续确认。重新报价会基于当前账户与预算版本再次核对。</view><view v-else class="notice notice--info note">确认后只建立订单，不代表已经支付。报价或资金版本变化时，服务端会要求重新评估。</view><view v-if="intent.status==='proposed'&&!expired" class="actions"><button class="primary-button" :loading="saving" @tap="confirm">确认建立订单</button><button class="secondary-button" :disabled="saving" @tap="reject">放弃意图</button></view><button v-else-if="expired||intent.status==='expired'||intent.status==='rejected'" class="primary-button full" @tap="retryQuote">重新选择并获取报价</button><button v-else-if="intent.orderId" class="primary-button full" @tap="Taro.redirectTo({url:`/pages/order/detail?id=${intent.orderId}`})">查看订单</button><view v-if="error" class="notice notice--error note">{{error}}</view></SectionCard></PageShell></template>
<style lang="scss">@use '../../styles/tokens' as *;.back{position:absolute;right:28px;top:calc(34px + env(safe-area-inset-top));width:64px;height:64px;border-radius:50%;font-size:44px}.title{font-size:36px;font-weight:740;line-height:1.4}.note{margin-top:24px;font-size:28px;line-height:1.65}.actions{display:grid;gap:16px;margin-top:28px}.actions button,.full{width:100%}.full{margin-top:28px}</style>
